import requests
import json
from Pizza import Pizza
from Order import Order
from Drinks import Drinks


def submitOrder(order):
    rsp = requests.post('https://uoftcsc301a2.herokuapp.com/create',
                        json=order.jsonify(), headers=headers)
    if rsp.status_code == 200:
        print(
            "Order submitted successfully order_number is " + rsp.text)
        order.order_number = rsp.text
        rsp = requests.post('https://uoftcsc301a2.herokuapp.com/update/'+order.order_number,
                            json=order.jsonify(), headers=headers)
        print(
            "Status of updating order " + order.order_number + ": " + str(rsp.status_code))
    else:
        print("submit failed, please try again")


""" def find_last_order_no():
    with open('order/last_order_no', 'r') as f:
        last_no = f.readline()
        new_no = int(last_no) + 1
        f.close()

    with open('order/last_order_no', 'w') as f:
        f.write(str(new_no))
    return str(new_no) """


def processOrderSubmission():
    still_ordering = True
    with open('order/Menu.json') as f:
        menu = json.load(f)
        f.close
    #order = Order(find_last_order_no())
    # order number will be generated by https://uoftcsc301a2.herokuapp.com/create
    # and return to client by a respose. Overhere, we just give a fake number
    order = Order("1")
    while (still_ordering):
        selection = input('''Select from the following:
        1. Add an item.
        2. Submit order.  
        Make your selection:''')
        if selection == "1":
            print('''which item do you want: 
                1. Pizza.
                2. Drinks.  ''')
            itemChoice = input("Make your Choice: ")
            if itemChoice == "1":
                pizza = input("Enter pizza name: ")
                while not pizza in menu["pizza"]["Type"].keys():
                    print("we don't provide this type of pizza")
                    pizza = input("Enter pizza name: ")
                size = input("Enter size (12, 15, 18): ")
                while size not in ["12", "15", "18"]:
                    print("please choose the available size")
                    size = input("Enter size (12, 15, 18): ")
                orderPizza = Pizza(pizza, int(size))
                additionalToppings = input(
                    "Do you want additional toppings (y/n)?")
                if (additionalToppings == "y"):
                    additionalToppings = []
                    stillAdding = True
                    print("Enter 'q' to finish adding toppings")
                    while (stillAdding):
                        newTopping = input("topping: ")
                        while newTopping not in menu["pizza"][
                                "Toppings"].keys() and newTopping != "q":
                            print("we don't have this topping")
                            newTopping = input("topping: ")
                        if (newTopping == "q"):
                            stillAdding = False
                        else:
                            additionalToppings.append(newTopping)
                    orderPizza.addToppings(additionalToppings)
                order.addItem(orderPizza)
            elif itemChoice == "2":
                drink = input("Enter drink's name: ")
                while drink not in menu["drinks"].keys():
                    print("we don't have this Drinks, please choose again")
                    drink = input("Enter drink's name: ")
                orderDrink = Drinks(drink)
                order.addItem(orderDrink)
        elif selection == "2":
            submitOrder(order)
            still_ordering = False
        else:
            print("invalid selection")


if __name__ == '__main__':
    headers = {'Content-Type': 'application/json'}
    base_url = 'https://uoftcsc301a2.herokuapp.com/'
    # base_url = 'http://127.0.0.1:5000/'
    # with open('order/Menu.json') as f:
    #     menu = json.load(f)
    #     f.close
    # r = requests.post(base_url + 'create_menu', data=json.dumps(menu),
    #                   headers=headers)
    # r = requests.get(base_url + 'retrieve/' + 'Menu')
    # print("Response body: " + r.text)

    while True:
        print('''Select a number for the action you would like to do: 
        1. Submit an order
        2. 
        3. 
        ''')
        selection = input("Make your selection: ")

        if selection == "1":
            processOrderSubmission()
        else:
            print("invalid selection")
